### ISSUE TITLE
binding to US locale results in wrong decimal point

### ISSUE THREAD

**Issue by frankolschewski** [paypal/rest-api-sample-app-java#3]
The sample app only works with US locale. For other locales I get an error like:

```
... {"name":"VALIDATION_ERROR","details":[{"field":"transactions[0].amount.total","issue" ...
```
The problem is in AppHelper.createPayment.

- Rule: Never use Double for reliable finance calculations, use BigDecimal instead.
- Hint: String.format uses the current locale. If you insist on a result in a particular locale, don't use it.

Change AppHelper.createPayment to this:

```
final BigDecimal total = new BigDecimal(order.getTax())
   .add(new BigDecimal(order.getShipping()))
   .add(new BigDecimal(order.getOrderAmount()));
amount.setTotal(total.toPlainString());
```

**Comment by jaypatel512** [comment]
Closing this issue based on inactivity. Please re-open if you are still facing this issue.
