### ISSUE TITLE
Doesnt accept more 3500$ when payment method is paypal

### ISSUE THREAD

**Issue by v2techs** [paypal/rest-api-sample-app-java#6]
We are trying to run this program when payment method is choosen as paypal and amount we are giving as 3500.
Credit card details and all other information are valid because it works well for small amount like 300 or 400$

Can this be checked please???

**Comment by jaypatel512** [comment]
This looks like an account issue, and not the REST API SDK Sample app. Can you please reach out to [Merchant Technical Support](https://developer.paypal.com/support/)
